project_id = "xdinmyztzvrcasvgupir"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[functions.ai-chat]
verify_jwt = true

[functions.ai-document-categorizer]
verify_jwt = true

[functions.create-expense]
verify_jwt = true

[functions.delete-expense]
verify_jwt = true

[functions.get-user-expenses]
verify_jwt = true

[functions.get-knowledge-base-by-user]
verify_jwt = true

[functions.create-knowledge-base-entry]
verify_jwt = true

[functions.update-knowledge-base-entry]
verify_jwt = true

[functions.delete-knowledge-base-entry]
verify_jwt = true

[functions.whatsapp-webhook]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.newsletter-subscribe]
verify_jwt = false

[functions.check-receipt-limit]
verify_jwt = true

[functions.create-web-call]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = true

[functions.create-portal-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

