// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhzymvjwwvgdysoqsunf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoenltdmp3d3ZnZHlzb3FzdW5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNjI2MDIsImV4cCI6MjA2NzczODYwMn0.T3s3qTbSRUWu41mPn_pRUamLfV7jZ_yEvl3Xeg6zLak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});